FIND_PATH(BOX2D_INCLUDE_DIR Box2D.h
	PATHS /usr/local/include /usr/include
	PATH_SUFFIXES Box2D
)

FIND_LIBRARY(BOX2D_LIBRARY NAMES Box2D
	PATHS /usr/local/lib /usr/lib
)

# handle the QUIETLY and REQUIRED arguments and set BOX2D_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(BOX2D DEFAULT_MSG BOX2D_LIBRARY BOX2D_INCLUDE_DIR)

IF(BOX2D_FOUND)
	SET(BOX2D_LIBRARIES ${BOX2D_LIBRARY})
ELSE(BOX2D_FOUND)
	SET(BOX2D_LIBRARIES)
ENDIF(BOX2D_FOUND)

MARK_AS_ADVANCED(BOX2D_LIBRARY BOX2D_INCLUDE_DIR)
