
FIND_PATH(
	COCOS2DX_DIR cocos2dx/include/cocos2d.h
	PATHS /usr/local/include /usr/include
	PATH_SUFFIXES cocos2dx
)

FIND_PATH(
	COCOS2DX_INCLUDE_DIR cocos2d.h
	PATHS ${COCOS2DX_DIR}/cocos2dx/include/ /usr/local/include /usr/include
	PATH_SUFFIXES cocos2dx
)

IF( "${CMAKE_SYSTEM}" MATCHES "Linux" )
	SET( COCOS2DX_LIBPATH ${COCOS2DX_DIR}/lib/linux )
	SET(
		COCOS2DX_INCLUDE_DIRS
		${COCOS2DX_DIR}/
		${COCOS2DX_DIR}/cocos2dx/
		${COCOS2DX_DIR}/cocos2dx/include/
		${COCOS2DX_DIR}/cocos2dx/platform/
		${COCOS2DX_DIR}/cocos2dx/platform/third_party/linux 
		${COCOS2DX_DIR}/Box2D
		${COCOS2DX_DIR}/CocosDenshion/include
	)
	ADD_DEFINITIONS( -DLINUX )
ENDIF()

# debug libs
FIND_LIBRARY(
	COCOS2DX_LIBRARY_DEBUG
	NAMES cocos2d
	PATHS ${COCOS2DX_LIBPATH}/Debug /usr/local/lib /usr/lib
)
FIND_LIBRARY(
	BOX2D_LIBRARY_DEBUG
	NAMES libbox2d.a
	PATHS ${COCOS2DX_LIBPATH}/Debug /usr/local/lib /usr/lib
)

# release libs
FIND_LIBRARY(
	COCOS2DX_LIBRARY_RELEASE
	NAMES cocos2d
	PATHS ${COCOS2DX_LIBPATH}/Release /usr/local/lib /usr/lib
)
FIND_LIBRARY(
	BOX2D_LIBRARY_RELEASE
	NAMES libbox2d.a
	PATHS ${COCOS2DX_LIBPATH}/Release /usr/local/lib /usr/lib
)

# merging libs
IF( COCOS2DX_LIBRARY_DEBUG )
	SET( COCOS2DX_LIBRARY ${COCOS2DX_LIBRARY_DEBUG} )
	SET( BOX2D_LIBRARY ${BOX2D_LIBRARY_DEBUG} )
ENDIF()

IF( COCOS2DX_LIBRARY_RELEASE )
	SET( COCOS2DX_LIBRARY ${COCOS2DX_LIBRARY} ${COCOS2DX_LIBRARY_RELEASE} )
	SET( BOX2D_LIBRARY ${BOX2DX_LIBRARY} ${BOX2D_LIBRARY_RELEASE} )
ENDIF()

SET( COCOS2DX_LIBRARIES ${COCOS2DX_LIBRARY} ${BOX2D_LIBRARY} )

# handle the QUIETLY and REQUIRED arguments and set COCOS2DX_FOUND to TRUE if
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(COCOS2DX DEFAULT_MSG COCOS2DX_LIBRARIES COCOS2DX_INCLUDE_DIRS)

MARK_AS_ADVANCED( COCOS2DX_LIBRARY COCOS2DX_INCLUDE_DIRS )

